[workspace.package]
edition = "2021"
license = "Apache-2.0"
authors = ["Carl von Ayres <cvonayres@fuelcellsystems.co.uk>"]
repository = "https://github.com/convyares-FCSL/rosrustext"
homepage = "https://github.com/convyares-FCSL/rosrustext"
description = "Explicit, testable ROS 2 lifecycle extensions for Rust"
rust-version = "1.75"

[workspace.dependencies]
thiserror = "2.0"
tracing = "0.1"
tokio = "1.48"

[workspace]
members = [
    "crates/rosrustext_core",
    "crates/rosrustext_roslibrust",
    "crates/rosrustext_msgs",
    "crates/rosrustext_rosrs",
]
exclude = [
    "crates/rosrustext_roslibrust/tools/rosrustext_lifecycle_proxy",
    "crates/rosrustext_roslibrust/tools/rosrustext_lifecycle_demo",
]
resolver = "2"
