[package]
name = "rosrustext_lifecycle_proxy"
version = "0.2.1"
edition = "2021"
license = "Apache-2.0"
authors = ["Carl von Ayres <cvonayres@fuelcellsystems.co.uk>"]
repository = "https://github.com/convyares-FCSL/rosrustext"
homepage = "https://github.com/convyares-FCSL/rosrustext"
description = "Rust lifecycle proxy for rosrustext_roslibrust nodes over rosbridge"
readme = "README.md"
exclude = ["interfaces", "interfaces/**"]

[dependencies]
roslibrust = { version = "0.18.0", features = ["rosbridge", "codegen"] }
tokio = { version = "1.48", features = ["macros", "rt-multi-thread", "sync", "time"] }
tracing = "0.1"
tracing-subscriber = "0.3"
rosrustext_core = { version = "0.4.0", path = "../../../rosrustext_core" }
rosrustext_roslibrust = { version = "0.2.1", path = "../.." }

[build-dependencies]
roslibrust = { version = "0.18.0", features = ["codegen"] }

[features]
default = []
bond = []

[workspace]

[patch.crates-io]
rosrustext_core = { path = "../../../rosrustext_core" }
